

# @name loginAdmin
@tokenAdmin = {{loginAdmin.response.headers.Authorization}}

POST http://127.0.0.1:3000/login
Content-Type: application/json

{
    "email": "pippo@gmail.com",
    "password": "11111111"
}



###

# @name loginUser
@tokenUser = {{loginUser.response.headers.Authorization}}

POST http://127.0.0.1:3000/login
Content-Type: application/json

{
    "email": "erminio@gmail.com",
    "password": "11111110"
}


###


GET http://127.0.0.1:3000/users/get?page=0&size=6
Authorization: Bearer {{tokenAdmin}}



###


GET http://127.0.0.1:3000/users/1/one
Authorization: Bearer {{tokenUser}}

###

GET http://127.0.0.1:3000/books/1/one
Authorization: Bearer {{tokenAdmin}}


###


POST http://127.0.0.1:8080/books/upload
Authorization: Bearer {{tokenUser}}
Content-Type: multipart/form-data; boundary=MfnBoundry

--MfnBoundry
Content-Disposition: form-data; name="imageFile"; filename="test.txt"
Content-Type: text/plain

sasaprova
--MfnBoundry--





###
GET http://127.0.0.1:8080/users/1/getTokenTime


###


POST http://127.0.0.1:3000/users/register
Content-Type: application/json

{
    "name": "cataldo",
    "email": "cat95@gmail.com",
    "password": "banana33"
}


###

GET http://localhost:8080/orders/inbox/all?page=1&size=3