




POST http://127.0.0.1:3000/service/addOrder
Content-Type: application/json

{
    "userId": 1,
    "books": [
        {"id": 1, "q": 1},
        {"id": 2, "q": 2},
        {"id": 3, "q": 1}
    ]
}






### creo l'ordine

GET http://127.0.0.1:3000/api/orders/1/create
Content-Type: application/json



###

POST http://127.0.0.1:3000/api/joinTables/create
Content-Type: application/json

{
    "order": 
    {
        "id": 16
    },
    "book":
    {
        "id": 3
    },
    "quantity": 7,
    "price": 0
}



###


GET http://127.0.0.1:3000/api/orders/1/all?page=0&size=100


###


GET http://127.0.0.1:3000/api/joinTables/create


###


GET http://127.0.0.1:3000/api/joinTables/3/count



###


GET http://127.0.0.1:8080/books/get?page=0&size=4